# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LutheringLavesLauncher Packing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: lastlive/nuitka-patchelf

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: show dependencies
        run: |
          nuitka --version

      - name: Packing
        run: |
          python -m nuitka --standalone --python-flag="-S" --follow-imports \
          --windows-console-mode="disable"  --windows-icon-from-ico="resource/launcher.ico" \
          --main="LutheringLavesLauncher.py"  --enable-plugins="pyside6"  --linux-icon="resource/launcher.ico" \
          --include-raw-dir=tools=tools   --include-raw-dir=Font=Font   --include-raw-dir=resource=resource

      - name: Get current time
        id: current-time
        run: |
          echo "timestamp=$(date -u +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "tag_name=launcher-${GITHUB_RUN_NUMBER}-$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Compress LutheringLavesLauncher.dist
        run: |
          mv LutheringLavesLauncher.dist LutheringLavesLauncher
          zip -r "LutheringLavesLauncher_${{ steps.current-time.outputs.timestamp }}.zip" LutheringLavesLauncher/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.current-time.outputs.tag_name }}
          name: LutheringLavesLauncher ${{ steps.current-time.outputs.timestamp }}
          generate_release_notes: true
          files: |
            LutheringLavesLauncher_${{ steps.current-time.outputs.timestamp }}.zip

      - name: Clean up
        run: |
          rm "LutheringLavesLauncher_${{ steps.current-time.outputs.timestamp }}.zip"
          rm -rf LutheringLavesLauncher/
          rm -rf LutheringLavesLauncher.dist/
          rm -rf LutheringLavesLauncher.build/
